/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.tristan_suud.view;
import me.tristan_suud.controller.MahasiswaController;
import me.tristan_suud.model.*;
import java.util.List;
import javax.swing.*;
/**
 *
 * @author LENOVO
 */
public class MahasiswaView extends javax.swing.JFrame {

    /**
     * Creates new form MahasiswaView
     */
    private MahasiswaController controller;
    
    public MahasiswaView() {
        initComponents();
        HibernateUtil.testConnection();
        this.controller = new MahasiswaController();
        loadMahasiswaTable();
    }
    
    public void loadMahasiswaTable(){
        List<ModelMahasiswa> listMahasiswa = controller.getAllMahasiswa();
        ModelTabelMahasiswa tableModel = new ModelTabelMahasiswa(listMahasiswa);
        
        dataTable.setModel(tableModel);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NPMLabel = new javax.swing.JLabel();
        NamaLabel = new javax.swing.JLabel();
        SemesterLabel = new javax.swing.JLabel();
        IPKLabel = new javax.swing.JLabel();
        IPKField = new javax.swing.JTextField();
        NPMField = new javax.swing.JTextField();
        NamaField = new javax.swing.JTextField();
        SemesterField = new javax.swing.JTextField();
        SimpanButton = new javax.swing.JButton();
        BuangButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NPMLabel.setText("NPM");

        NamaLabel.setText("Nama");

        SemesterLabel.setText("Semester");

        IPKLabel.setText("IPK");

        IPKField.setColumns(25);
        IPKField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPKFieldActionPerformed(evt);
            }
        });

        NPMField.setColumns(25);
        NPMField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NPMFieldActionPerformed(evt);
            }
        });

        NamaField.setColumns(25);
        NamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaFieldActionPerformed(evt);
            }
        });

        SemesterField.setColumns(25);
        SemesterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterFieldActionPerformed(evt);
            }
        });

        SimpanButton.setText("Simpan");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });

        BuangButton.setText("Buang");
        BuangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuangButtonActionPerformed(evt);
            }
        });

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IPKLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaLabel)
                                    .addComponent(NPMLabel)
                                    .addComponent(SemesterLabel))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NPMField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IPKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SimpanButton)
                        .addGap(18, 18, 18)
                        .addComponent(BuangButton)
                        .addGap(18, 18, 18)
                        .addComponent(RefreshButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NPMLabel)
                    .addComponent(NPMField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaLabel)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemesterLabel)
                    .addComponent(SemesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPKLabel)
                    .addComponent(IPKField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanButton)
                    .addComponent(BuangButton)
                    .addComponent(RefreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IPKFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPKFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPKFieldActionPerformed

    private void NPMFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NPMFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NPMFieldActionPerformed

    private void NamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaFieldActionPerformed

    private void SemesterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterFieldActionPerformed

    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed
        // TODO add your handling code here:
        String npm = getNPMField().getText();
        String nama = getNamaField().getText();
        int semester = Integer.parseInt(getSemesterField().getText());
        float ipk = Float.parseFloat(getIPKField().getText());
        ModelMahasiswa mahasiswa = new ModelMahasiswa(0 , npm, nama, semester, ipk);
        System.out.println(mahasiswa.getIpk());
        System.out.println(mahasiswa.getNama());
        System.out.println(mahasiswa.getSemester());
        System.out.println(mahasiswa.getNpm());
        
        controller.addMhs(mahasiswa);
        loadMahasiswaTable();
    }//GEN-LAST:event_SimpanButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        loadMahasiswaTable();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void BuangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuangButtonActionPerformed
        JTextField idField = new JTextField(5);
        
        JPanel panel = new JPanel();
        panel.add(new JLabel("Masukkan id yang ingin dihapus: "));
        panel.add(idField);
        
        int result = JOptionPane.showConfirmDialog(null, panel, "Hapus Mahasiswa", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION){
            try {
                int id = Integer.parseInt(idField.getText());
                controller.deleteMhs(id);
                JOptionPane.showConfirmDialog(null, "Data berhasil dihapuskan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e){
                JOptionPane.showConfirmDialog(null, "Data gagal dihapuskan, id harus berupa angka.", "error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_BuangButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuangButton;
    private javax.swing.JTextField IPKField;
    private javax.swing.JLabel IPKLabel;
    private javax.swing.JTextField NPMField;
    private javax.swing.JLabel NPMLabel;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextField SemesterField;
    private javax.swing.JLabel SemesterLabel;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public MahasiswaController getController() {
        return controller;
    }

    public void setController(MahasiswaController controller) {
        this.controller = controller;
    }

    public JButton getBuangButton() {
        return BuangButton;
    }

    public void setBuangButton(JButton BuangButton) {
        this.BuangButton = BuangButton;
    }

    public JTextField getIPKField() {
        return IPKField;
    }

    public void setIPKField(JTextField IPKField) {
        this.IPKField = IPKField;
    }

    public JLabel getIPKLabel() {
        return IPKLabel;
    }

    public void setIPKLabel(JLabel IPKLabel) {
        this.IPKLabel = IPKLabel;
    }

    public JTextField getNPMField() {
        return NPMField;
    }

    public void setNPMField(JTextField NPMField) {
        this.NPMField = NPMField;
    }

    public JLabel getNPMLabel() {
        return NPMLabel;
    }

    public void setNPMLabel(JLabel NPMLabel) {
        this.NPMLabel = NPMLabel;
    }

    public JTextField getNamaField() {
        return NamaField;
    }

    public void setNamaField(JTextField NamaField) {
        this.NamaField = NamaField;
    }

    public JLabel getNamaLabel() {
        return NamaLabel;
    }

    public void setNamaLabel(JLabel NamaLabel) {
        this.NamaLabel = NamaLabel;
    }

    public JButton getRefreshButton() {
        return RefreshButton;
    }

    public void setRefreshButton(JButton RefreshButton) {
        this.RefreshButton = RefreshButton;
    }

    public JTextField getSemesterField() {
        return SemesterField;
    }

    public void setSemesterField(JTextField SemesterField) {
        this.SemesterField = SemesterField;
    }

    public JLabel getSemesterLabel() {
        return SemesterLabel;
    }

    public void setSemesterLabel(JLabel SemesterLabel) {
        this.SemesterLabel = SemesterLabel;
    }

    public JButton getSimpanButton() {
        return SimpanButton;
    }

    public void setSimpanButton(JButton SimpanButton) {
        this.SimpanButton = SimpanButton;
    }

    public JTable getDataTable() {
        return dataTable;
    }

    public void setDataTable(JTable dataTable) {
        this.dataTable = dataTable;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    

}
